name: CI

on:
  push:
    branches: [master]
  pull_request:

env:
  MIX_ENV: test
  CI_ELIXIR_VERSION: "1.20"
  CI_OTP_VERSION: "28.5"
  CI_BEAM_VERSION: "1.20-28.5"

jobs:
  test:
    name: Unit Test (Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }})
    strategy:
      fail-fast: false
      matrix:
        include:
          # https://hexdocs.pm/elixir/compatibility-and-deprecations.html
          # compatibility between Elixir and Erlang/OTP
          - elixir: "1.17"
            otp: "27.3"
          - elixir: "1.18"
            otp: "27.3"
          - elixir: "1.19"
            otp: "28.5"
          - elixir: "1.20"
            otp: "28.5"

    runs-on: blacksmith-2vcpu-ubuntu-2404

    steps:
      - uses: actions/checkout@v6.0.3

      - name: Dependency cache
        uses: actions/cache@v5.0.5
        with:
          path: |
            deps
            _build
          key: test-${{ matrix.elixir }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            test-${{ matrix.elixir }}-
            mix-test-${{ runner.os }}-
            mix-test-

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install dependencies
        run: |
          mix deps.get
          mix deps.compile

      - name: Check retired and unused dependencies
        run: |
          mix hex.audit
          mix deps.unlock --check-unused

      - name: Run tests
        run: mix test

  formatter:
    name: Formatter
    runs-on: blacksmith-2vcpu-ubuntu-2404

    steps:
      - uses: actions/checkout@v6.0.3

      - name: Dependency cache
        uses: actions/cache@v5.0.5
        with:
          path: |
            deps
            _build
          key: fmt-${{ env.CI_BEAM_VERSION }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            fmt-${{ env.CI_BEAM_VERSION }}-
            mix-fmt-${{ runner.os }}-
            mix-fmt-

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.CI_OTP_VERSION }}
          elixir-version: ${{ env.CI_ELIXIR_VERSION }}

      - name: Install dependencies
        run: mix deps.get

      - name: Run Formatter
        run: mix fmt

  linter:
    name: Linter
    runs-on: blacksmith-2vcpu-ubuntu-2404

    steps:
      - uses: actions/checkout@v6.0.3

      - name: Dependency cache
        uses: actions/cache@v5.0.5
        with:
          path: |
            deps
            _build
          key: lint-${{ env.CI_BEAM_VERSION }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            lint-${{ env.CI_BEAM_VERSION }}-
            mix-lint-${{ runner.os }}-
            mix-lint-

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.CI_OTP_VERSION }}
          elixir-version: ${{ env.CI_ELIXIR_VERSION }}

      - name: Install dependencies
        run: |
          mix deps.get
          mix deps.compile

      - name: Run Linter
        run: mix credo

  dialyzer:
    name: Dialyzer
    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - uses: actions/checkout@v6.0.3

      - name: Dependency cache
        uses: actions/cache@v5.0.5
        with:
          path: |
            deps
            _build
          key: dialyzer-${{ env.CI_BEAM_VERSION }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            dialyzer-${{ env.CI_BEAM_VERSION }}-
            mix-dev-dialyzer-${{ runner.os }}-
            mix-dev-dialyzer-

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.CI_OTP_VERSION }}
          elixir-version: ${{ env.CI_ELIXIR_VERSION }}

      - name: Install dependencies
        run: |
          mix deps.get
          mix deps.compile

      - name: Run Dialyzer
        run: mix dialyzer
